server:
  port: 8080

spring:
  application:
    name: ticketing-core

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  data:
    redis:
      host: localhost
      port: 6379

queue:
  base-url: http://localhost:8082